# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ffde40b4fa8f492b09fae443000208aeadb77a59524d64e8dc69f36e712f79ca9ccda0c2c6c9749c0677ebc60fdcb128331fce6f6df2f9cf9b82e862c923137

test:
  secret_key_base: 7c42aa681a164666116752e94d2f05a7ad986c71e96859365067fe3d573dc19606f99463a7a70075767964a8b45e3a488b7e7535202aef1c64dac56e11861577

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
